##### Map #####
"""
a1 a2 a3 a4 x = player home
-------------
|  |  |  |  | a4
-------------
|  |X |  |  | b4
-------------
|  |  |  |  | c4
-------------
|  |  |  |  | d4
-------------
"""

zonemap = {
        'a1': {
            'ZoneName': "",
            'Description': "Welcome to A1",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': '',
            'South': 'b1',
            'East': '',
            'West': 'a2',
        },
        'a2': {
            'ZoneName': "",
            'Description': "Welcome to A2",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': '',
            'South': 'b3',
            'East': 'a1',
            'West': 'a3',
        },
        'a3': {
            'ZoneName': "",
            'Description': "Welcome to A3",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': '',
            'South': 'b3',
            'East': 'a3',
            'West': 'a4',
        },
        'a4': {
            'ZoneName': "",
            'Description': "Welcome to A4",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': '',
            'South': 'b4',
            'East': 'a4',
            'West': '',
        },
        'b1': {
            'ZoneName': "",
            'Description': "Welcome to B1",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': 'a1',
            'South': 'c1',
            'East': '',
            'West': 'b2',
        },
        'b2': {
            'ZoneName': "",
            'Description': "This is your home.",
            'Examine': "You look around at your wonderful home.",
            'Solved': True,
            'North': 'a2',
            'South': 'c2',
            'East': 'b1',
            'West': 'b3'
        },
        'b3': {
            'ZoneName': "",
            'Description': "Welcome to B3",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': 'a3',
            'South': 'c3',
            'East': 'b2',
            'West': 'b4',
        },
        'b4': {
            'ZoneName': "",
            'Description': "Welcome to B4",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': 'a4',
            'South': 'c4',
            'East': 'b3',
            'West': '',
        },
        'c1': {
            'ZoneName': "",
            'Description': "Welcome to C1",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': 'b1',
            'South': 'd1',
            'East': '',
            'West': 'c2',
        },
        'c2': {
            'ZoneName': "",
            'Description': "Welcome to C2",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': 'b2',
            'South': 'd2',
            'East': 'c1',
            'West': 'c3',
        },
        'c3': {
            'ZoneName': "",
            'Description': "Welcome to C3",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': 'b3',
            'South': 'd3',
            'East': 'c2',
            'West': 'c4',
        },
        'c4': {
            'ZoneName': "",
            'Description': "Welcome to C4",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': 'b4',
            'South': 'd4',
            'East': 'c3',
            'West': '',
        },
        'd1': {
            'ZoneName': "",
            'Description': "Welcome to D1",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': 'c1',
            'South': '',
            'East': '',
            'West': 'd2',
        },
        'd2': {
            'ZoneName': "",
            'Description': "Welcome to D2",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': 'c2',
            'South': '',
            'East': 'd1',
            'West': 'd3',
        },
        'd3': {
            'ZoneName': "",
            'Description': "Welcome to D3",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': 'c3',
            'South': '',
            'East': 'd2',
            'West': 'd4',
        },
        'd4': {
            'ZoneName': "",
            'Description': "Welcome to D4",
            'Examine': "Nothing yet",
            'Riddle': '',
            'Answer': '',
            'Solved': False,
            'North': 'c4',
            'South': '',
            'East': 'd3',
            'West': '',
        }
}